version: '3.8'
services:
   java:
      image: accounttolearn/marketlist:int
      environment:
         PORTA: 9001
      ports:
         - "9001:9001"
      volumes:
         - "/home/docker/volumes:/var/www/volumes"
      networks:
         - minha-rede
      deploy:
         replicas: 1
         restart_policy:
            condition: on-failure
         placement:
            constraints:
               - "node.role==worker"
               - "node.labels.ambiente==hom"
networks:
   minha-rede:
      driver: overlay
