version: '3.8'
services:
   java:
      image: localhost:5001/marketlist:hom
      environment:
         PORTA: 9002
      ports:
         - "9002:9002"
      volumes:
         - "/home/docker/volumes:/var/www/volumes"
      networks:
         - minha-rede
      deploy:
         replicas: 1
         restart_policy:
            condition: on-failure
         placement:
            max_replicas_per_node: 1
            constraints:
               - "node.role==worker"
               - "node.labels.vm==hom"
networks:
   minha-rede:
      driver: overlay
