version: '3'
services:
   java:
      build: .
      image: java
      container_name: java
      ports: 
         - "9000:9000"
      networks: 
         - minha-rede
networks:
   minha-rede:
      driver: bridge