version: '3.8'
services:
   registry:
      image: registry:2
      hostname: registry
      ports:
         - "5001:5000"
      networks:
         - minha-rede
      deploy:
         replicas: 1
         restart_policy:
            condition: on-failure
         placement:
            max_replicas_per_node: 1
            constraints:
               - "node.role==manager"
               - "node.labels.vm==reg"
networks:
   minha-rede:
      driver: overlay
